### ISSUE TITLE
apollo-codegen throws error

### ISSUE THREAD

**Issue by JanGorman** [apollostack/apollo-ios#28]
Hello there,

I was about to try the library but got stuck at the schema download step:

`apollo-codegen download-schema {server url} --output schema.json`

```bash
module.js:340
    throw err;
          ^
Error: Cannot find module '.'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/j.gorman/.nvm/v0.10.36/lib/node_modules/apollo-codegen/lib/cli.js:32:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

It failed before that with `Error: Cannot find module 'process'`, I ran `npm install -g process` which fixed that but this error now isn't as easy to figure out. Any hints?

**Comment by martijnwalraven** [comment]
Hmmm, I'm not sure what is going on here, but you shouldn't have to `npm install` process because it is a built-in module in Node.

So I suspect there might be something wrong with your Node installation. I don't know if this is related, but it also seems you're running Node 0.10, which is a rather old version.

Could you retry with the more recent Node 4 or 6?

**Comment by JanGorman** [comment]
Cheers for the quick response. I'll give that a try.

**Comment by JanGorman** [comment]
And indeed that did the trick. Thanks 🎉
